name: "example_python_c"
backend: "python"
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
input [
  {
    name: "INPUT1"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
output [
  {
    name: "OUTPUT1"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]

instance_group [
  {
    count: 2
    kind: KIND_CPU
    rate_limiter {
      resources [
        {
          name: "R1"
          count: 5
        },
        {
          name: "R2"
          count: 5
        }
      ] 
      priority: 1
    }
  }
]
